name: Generate UML

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET tool (PlantUmlClassDiagramGenerator)
        run: dotnet tool install --global PlantUmlClassDiagramGenerator

      - name: Debug — list all C# files
        run: Get-ChildItem -Recurse -Filter *.cs

      - name: Generate UML
        run: |
          $Path = "${{ github.workspace }}"
          Write-Host Path: $Path
          puml-gen -i $Path -o $Path/diagram.puml -r

      - name: Upload UML diagram
        uses: actions/upload-artifact@v4
        with:
          name: UML
          path: diagram.puml
