name: Generate UML

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Generator
        run: dotnet tool install --global PlantUmlClassDiagramGenerator

      - name: Generate UML
        run: puml-gen --input ./src --output ./diagram.puml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UML
          path: diagram.puml
